name: Kaggle kernel actions

on:
  push:
    branches:
      - softwarex-modifs

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']
    name: Python ${{ matrix.python-version }} ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Push kernel to kaggle
      uses: joelhanson/kaggle-kernel-actions@v2
      with:
        kaggle_username: ${{ secrets.KAGGLE_USERNAME }}
        kaggle_key: ${{ secrets.KAGGLE_KEY }}
        kaggle_make_new_kernel: true
        kernel_id: majedjaber/gpml-reproducible-capsule
        language: python
        competition: titanic
